version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/go/src/github.com/akitasoftware/akita-change-management-demo
    steps:
      - checkout
      
      - run:
          name: Install golang
          command: |
            sudo apt-get update -y
            sudo apt-get install -y golang
      
      - run:
          name: Get Akita Docker Image
          command: docker pull akitasoftware/cli:latest
      
      - run:
          name: Start Akita Client
          command: |
                  docker run --rm -d \
                        --env CI="${CI}" \
                        --env CIRCLECI="${CIRCLECI}" \
                        --env CIRCLE_REPOSITORY_URL="${CIRCLE_REPOSITORY_URL}" \
                        --env CIRCLE_BRANCH="${CIRCLE_BRANCH}" \
                        --env CIRCLE_SHA1="${CIRCLE_SHA1}" \
                        --env CIRCLE_PULL_REQUEST="${CIRCLE_PULL_REQUEST}" \
                        --env CIRCLE_BUILD_URL="${CIRCLE_BUILD_URL}" \
                        --env AKITA_API_KEY_ID=${AKITA_API_KEY_ID} \
                        --env AKITA_API_KEY_SECRET=${AKITA_API_KEY_SECRET} \
                        --network=host \
                        --name akita \
                        akitasoftware/cli:latest learn \
                        --service akita-change-management-demo \
                        --port 8080
          background: true

      - run: 
          name: Start App Server
          command: go run .
          background: true
          
      - run: 
          name: Wait for App Server and Akita to start
          command: sleep 5
      
      - run: 
          name: Run Integration Tests
          command: ./test/integration-test.sh
        
      - run:
          name: Wait for Akita to build
          command: sleep 5
      
      - run:
          name: Stop Akita SuperLearn
          command: docker kill --signal=SIGINT akita
